"""payments table and awaiting_payment status

Revision ID: 6dfbd0fb417d
Revises: a624541b082f
Create Date: 2026-07-14 13:55:05.830399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dfbd0fb417d'
down_revision: Union[str, None] = 'a624541b082f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alembic's autogenerate does NOT add new members to an existing Postgres ENUM — it
    # silently ignores them. Without this line the `order_status` type has no
    # 'awaiting_payment' value and every prepaid order fails to insert. Added by hand.
    #
    # IF NOT EXISTS makes it re-runnable. ALTER TYPE ... ADD VALUE is allowed inside a
    # transaction on PG 12+ so long as the new value isn't USED in the same transaction,
    # which it isn't here.
    # NOTE the case: SQLAlchemy's Enum stores the member NAME ("AWAITING_PAYMENT"), not
    # its value ("awaiting_payment"). The existing labels are all uppercase. Adding the
    # lowercase spelling here would look right and still fail every insert.
    op.execute("ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'AWAITING_PAYMENT'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('JAZZCASH', 'EASYPAISA', 'FAKE', name='payment_provider'), nullable=False),
    sa.Column('txn_ref', sa.String(length=64), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PAID', 'FAILED', 'EXPIRED', name='payment_attempt_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_ref', name='uq_payments_txn_ref')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_ref'), 'payments', ['provider_ref'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_expires', 'payments', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_payments_txn_ref'), 'payments', ['txn_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_txn_ref'), table_name='payments')
    op.drop_index('ix_payments_status_expires', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_ref'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
