"""working hours, subscription plans, order ratings

Revision ID: a624541b082f
Revises: aecfd70e7074
Create Date: 2026-07-14 13:06:35.332308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a624541b082f'
down_revision: Union[str, None] = 'aecfd70e7074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_subscription_plans_name')
    )
    op.create_table('restaurant_working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.Column('crosses_midnight', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_working_hours_day'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurant_working_hours_restaurant_id'), 'restaurant_working_hours', ['restaurant_id'], unique=False)
    op.create_table('order_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_order_ratings_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_order_ratings_order')
    )
    op.create_index(op.f('ix_order_ratings_customer_id'), 'order_ratings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_ratings_order_id'), 'order_ratings', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_ratings_restaurant_id'), 'order_ratings', ['restaurant_id'], unique=False)
    op.add_column('restaurants', sa.Column('subscription_plan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_restaurants_subscription_plan_id'), 'restaurants', ['subscription_plan_id'], unique=False)
    op.create_foreign_key(None, 'restaurants', 'subscription_plans', ['subscription_plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.drop_index(op.f('ix_restaurants_subscription_plan_id'), table_name='restaurants')
    op.drop_column('restaurants', 'subscription_plan_id')
    op.drop_index(op.f('ix_order_ratings_restaurant_id'), table_name='order_ratings')
    op.drop_index(op.f('ix_order_ratings_order_id'), table_name='order_ratings')
    op.drop_index(op.f('ix_order_ratings_customer_id'), table_name='order_ratings')
    op.drop_table('order_ratings')
    op.drop_index(op.f('ix_restaurant_working_hours_restaurant_id'), table_name='restaurant_working_hours')
    op.drop_table('restaurant_working_hours')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
